import pandas as pd
from io import StringIO

# Sample data for testing
data = """order_id,customer_id,order_date,product_id,product_name,product_price,quantity
1,1,2021-01-01,101,Product A,10.0,1
2,2,2021-02-01,102,Product B,20.0,2
3,1,2021-02-15,101,Product A,10.0,2
4,3,2021-03-01,103,Product C,30.0,1
5,2,2021-03-15,104,Product D,40.0,1
6,1,2021-03-20,101,Product A,10.0,3
7,3,2021-04-01,105,Product E,50.0,1
"""

def read_data(data):
    """
    Read the data from a string.
    """
    return pd.read_csv(StringIO(data))

def compute_monthly_revenue(df):
    """
    Compute the total revenue generated by the online store for each month in the dataset.
    """
    df['order_date'] = pd.to_datetime(df['order_date'])
    df['revenue'] = df['product_price'] * df['quantity']
    monthly_revenue = df.groupby(df['order_date'].dt.to_period('M'))['revenue'].sum().reset_index()
    monthly_revenue.columns = ['month', 'total_revenue']
    return monthly_revenue

def compute_product_revenue(df):
    """
    Compute the total revenue generated by each product in the dataset.
    """
    product_revenue = df.groupby('product_name')['revenue'].sum().reset_index()
    product_revenue.columns = ['product_name', 'total_revenue']
    return product_revenue

def compute_customer_revenue(df):
    """
    Compute the total revenue generated by each customer in the dataset.
    """
    customer_revenue = df.groupby('customer_id')['revenue'].sum().reset_index()
    customer_revenue.columns = ['customer_id', 'total_revenue']
    return customer_revenue

def identify_top_customers(df, top_n=10):
    """
    Identify the top N customers by revenue generated.
    """
    customer_revenue = compute_customer_revenue(df)
    top_customers = customer_revenue.sort_values(by='total_revenue', ascending=False).head(top_n)
    return top_customers

def main():
    # Read the sample data
    df = read_data(data)

    monthly_revenue = compute_monthly_revenue(df)
    print("Monthly Revenue:")
    print(monthly_revenue)

    product_revenue = compute_product_revenue(df)
    print("\nProduct Revenue:")
    print(product_revenue)

    customer_revenue = compute_customer_revenue(df)
    print("\nCustomer Revenue:")
    print(customer_revenue)

    top_customers = identify_top_customers(df)
    print("\nTop Customers by Revenue:")
    print(top_customers)

if __name__ == "__main__":
    main()
